name: shop_${SHOP_ID:-0}
services:
  prestashop:
    container_name: prestashop-${SHOP_ID:-0}
    build: .
    environment:
      - PS_DOMAIN=${PS_DOMAIN}
      - SHOP_ID=${SHOP_ID:-0} 
    volumes:
      - ./prestashop.zip:/var/www/html/prestashop.zip
      - ./info.php:/var/www/html/info.php
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./scripts/install_cli.sh:/install_cli.sh
    ports:
      - "${PS_PORT:-80}:80"
    command: >
      bash -c "
        unzip -o /var/www/html/prestashop.zip -d /var/www/html/ && \
        bash /install_cli.sh && \
        mkdir -p /var/www/html/var/cache/prod /var/www/html/var/cache/dev /var/www/html/var/logs && \
        chmod -R 777 /var/www/html/var && \
        chmod 777 /tmp && \
        rm -rf /var/www/html/var/cache/* && \
        chown -R www-data:www-data /var/www/html && \
        apache2ctl -D FOREGROUND
      "
    networks:
      - prestashop_network

  mysql:
    container_name: mysql-${SHOP_ID:-0}
    restart: unless-stopped
    image: mariadb:lts
    environment:
      TZ: Europe/Paris
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_PORT: 3306
      MYSQL_DATABASE: prestashop
    ports:
      - "${MYSQL_PORT:-3300}:3306" 
    networks:
      - prestashop_network
      
  phpmyadmin:
      container_name: phpmyadmin-${SHOP_ID:-0}
      image: phpmyadmin:latest
      ports:
      - "${PMA_PORT:-3000}:80"
      environment:
        - PMA_HOST=mysql-${SHOP_ID:-0}
        - PMA_PORT=3306
        - PMA_USER=prestashop
        - PMA_PASSWORD=prestashop
        - MYSQL_ROOT_PASSWORD=prestashop
      networks:
        - prestashop_network 

  mytun:
    restart: always
    image: cloudflare/cloudflared:latest
    command: tunnel --config /config.yml run
    volumes:
    - ./myTun/config/mytun-config.yml:/config.yml:ro
    - ./myTun/config/mytun-credentials.json:/credentials.json:ro
    networks:
    - prestashop_network

networks:
  prestashop_network:
    # driver: bridge
    external: true
    name: prestashop_global

  