name: shop_zip
services:
  prestashop:
    build: .
    environment:
      - PS_DOMAIN=${PS_DOMAIN}
    volumes:
      - ./prestashop.zip:/var/www/html/prestashop.zip
      - ./info.php:/var/www/html/info.php
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./install_cli.sh:/install_cli.sh
    ports:
      - "${PS_PORT:-80}:80"
    command: >
      bash -c "
        unzip -o /var/www/html/prestashop.zip -d /var/www/html/ && \
        chown -R www-data:www-data /var/www/html && \
        bash /install_cli.sh && \
        apache2ctl -D FOREGROUND
      "
    networks:
      - prestashop_network

  mysql:
    restart: unless-stopped
    image: mariadb:lts
    environment:
      TZ: Europe/Paris
      MYSQL_HOST: mysql
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_PORT: 3306
      MYSQL_DATABASE: prestashop
    ports:
      - "${MYSQL_PORT:-3307}:3306" 
    networks:
      - prestashop_network
      
  phpmyadmin:
      image: phpmyadmin:latest
      ports:
      - "${PMA_PORT:-3007}:80"
      environment:
        - PMA_HOST=mysql
        - PMA_PORT=3306
        - PMA_USER=prestashop
        - PMA_PASSWORD=prestashop
        - MYSQL_ROOT_PASSWORD=prestashop
      networks:
        - prestashop_network 

  mytun:
    restart: always
    image: cloudflare/cloudflared:latest
    command: tunnel --config /config.yml run
    volumes:
    - ./myTun/config/mytun-config.yml:/config.yml:ro
    - ./myTun/config/mytun-credentials.json:/credentials.json:ro
    networks:
    - prestashop_network

networks:
  prestashop_network:
    driver: bridge

  